config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :questions

  resources :questions do
    resources :answers
  end

  get "/sign-in" => "sessions#new"
  post "/sign-in" => "sessions#create"
  get "/sign-out" => "sessions#destroy", as: :sign_out

  root :to => 'questions#index'

  get "/admin" => "admin#index"
  # namespace :admin do
  #   get '', to: 'dashboard#index', as: '/'
  # end
  
end

app/models/answer.rb
class Answer<ActiveRecord::Base
  validates_presence_of :content
  belongs_to :question
  belongs_to :user
  has_many :votes, as: :votable

  def vote_count
    total = 0
    self.votes.each do |vote|
      total += vote.count
    end
    return total
  end

  default_scope {order('created_at DESC')}
end

app/models/question.rb
class Question<ActiveRecord::Base
  validates_presence_of :title
  belongs_to :user
  has_many :answers
  has_many :votes, as: :votable

  default_scope {order('created_at DESC')}

  before_save :append_question_mark

  def vote_count
    total = 0
    self.votes.each do |vote|
      total += vote.count
    end
    return total
  end

  def sorted_answers
    self.answers.sort_by { |a| (a.vote_count) }.reverse!
  end

  private
  def append_question_mark
    unless self.title.scan(/[?]/).any?
      self.title += "?"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :username, :email
  has_many :questions
  has_many :answers

  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :votable, polymorphic: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @questions = Question.all
    @answers = Answer.all
    @users = User.all
  end

end

app/controllers/answers_controller.rb
class AnswersController<ApplicationController

  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user

    if @answer.save
      UserMailer.question_answered(@question.user, @question, @answer).deliver_now
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])

    if params[:f] # if voting
      vote_helper params[:f][:votes]
    else # normal model update
      if @answer.update(answer_params)
        redirect_to admin_path
      else
       render :edit
      end
    end
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to admin_path
  end

  private
  def answer_params
    params.require(:answer).permit(:content)
  end

  def vote_helper(vote_count)
    @vote = Vote.where(user_id: current_user.id, votable_id: @answer.id, votable_type: 'Answer')
    if @vote.any?
      flash[:notice] = 'You\'ve already voted.'
    else
      @answer.votes.create(count: vote_count, user_id: current_user.id, votable_id: @answer.id, votable_type: 'Answer')
    end
     redirect_to question_path(@question)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user

    if @question.save
      UserMailer.thank_you_question(current_user).deliver_now
      flash[:notice] = "Question added successfully!"
      redirect_to questions_path
    else
      render :new
    end
  end

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.sorted_answers
  end

  def update
    @question = Question.find(params[:id])
    if params[:f] # if voting
      vote_helper params[:f][:votes]
    else # normal model update
      if @question.update(question_params)
        redirect_to admin_path
      else
       render :edit
      end
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def destroy
    @question = Question.find(params[:id])
    @question.answers.each do |answer|
      answer.destroy
    end
    @question.destroy
    redirect_to admin_path
  end

  private
  def question_params
    params.require(:question).permit(:title)
  end

  def vote_helper(vote_count)
    @vote = Vote.where(user_id: current_user.id, votable_id: @question.id, votable_type: 'Question')
    if @vote.any?
      flash[:notice] = 'You\'ve already voted.'
    else
      @question.votes.create(count: vote_count, user_id: current_user.id, votable_id: @question.id, votable_type: 'Question')
    end
     redirect_to question_path(@question)
  end
end

app/controllers/sessions_controller.rb
class SessionsController<ApplicationController

  def create
    @user = User.authenticate(params[:email], params[:password])

    if @user
      flash[:notice] = "You've been logged in!"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "There was a problem logging you in"
      redirect_to sign_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You\'ve been logged out successfully.'
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Welcome to the site, #{@user.username}!"
      UserMailer.signup_confirmation(@user).deliver_now
      redirect_to sign_in_path
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<h1>Admin</h1>

<h3>Questions</h3>
<ul>
  <% @questions.each do |question| %>
    <li>
      <%= link_to "#{question.title} by #{question.user.username}, #{question.created_at.strftime("created on %m/%d/%Y at %I:%M%p")}", question_path(question) %>
      | <%= link_to "Delete", question_path(question), :data => {:confirm => "Are you sure?", :method => "delete"}, class: 'delete-question' %> |
      <%= link_to "Edit", edit_question_path(question), class: 'edit-question' %>
    </li>
    <ul>
      <% question.answers.each do |answer| %>
      <li>
        <%= link_to "#{answer.content} by #{answer.user.username}, #{answer.created_at.strftime("created on %m/%d/%Y at %I:%M%p")}", question_path(question) %>
        | <%= link_to "Delete", question_answer_path(question, answer), :data => {:confirm => "Are you sure?", :method => "delete"}, class: 'delete-answer' %> |
        <%= link_to "Edit", edit_question_answer_path(question, answer), class: 'edit-answer' %>
      </li>
      <% end %>
    </ul>
  <% end %>
</ul>


  <%= link_to "Ask Question", new_question_path %>

app/views/answers/_form.html.erb
 <%= render "layouts/errors", :object => @answer %>

 <%= form_for [@question, @answer] do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content, :autofocus => 'autofocus' %>
  <%= f.submit "Add Answer" %>
<% end %>

app/views/answers/edit.html.erb
<h1>Edit</h1>

<%= render "form" %>

app/views/answers/new.html.erb
<h1>Add a Answer</h1>

<%= render "form" %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_formArrows.html.erb
<%= form_for object do |f| %>
  <%= hidden_field(:f, :votes, :value => '1') %>
  <%= image_submit_tag('upArrow.png', :class => "arrow-icon", :id => 'up-vote') %>
<% end %>

<%= form_for object do |f| %>
  <%= hidden_field(:f, :votes, :value => '-1') %>
  <%= image_submit_tag('downArrow.png', :class => "arrow-icon", :id => 'down-vote') %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Stack Overflow</a>
      </div>

       <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <% if current_user.is_admin %>
            <li><%= link_to 'Admin', admin_path %></li>
          <% end %>
          <li><%= link_to 'Your Profile', user_path(current_user) %></li>
          <li><%= link_to "Sign Out", sign_out_path, {:id => "nav-sign-out"} %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_path, {:id => "nav-sign-up"} %></li>
          <li><%= link_to "Sign In", sign_in_path, {:id => "nav-sign-in"} %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <%= flash[:alert] %>
  <%= flash[:notice] %>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/questions/_form.html.erb
<%= render 'layouts/errors', :object => @question %>

<%= form_for @question do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => 'autofocus' %>
  <%= f.submit "Ask Question"%>
<% end %>

app/views/questions/index.html.erb
<h1>Questions</h1>
<ul>
  <% @questions.each do |question| %>
    <li><%= link_to "#{question.title} by #{question.user.username}, #{question.created_at.strftime("created on %m/%d/%Y at %I:%M%p")}", question_path(question) %></li>
  <% end %>
</ul>

<% if current_user %>
  <%= link_to "Ask Question", new_question_path %>
<% else %>
 <p>
   <%= link_to 'Sign In', sign_in_path %> to ask a Question
 </p>
<% end %>

app/views/questions/new.html.erb
<h1>Ask a question!</h1>
<%= render "form" %>

app/views/questions/show.html.erb
<h3>Question</h3>
<div class="row">
  <div class="col-xs-2 question-voting">
    <%= render 'layouts/formArrows', :object => @question %>
  </div>
  <div class="col-xs-10">
    <h3>
      <%= @question.title %>, By: <%= @question.user.username %>
      <small>Current Votes: <%= @question.vote_count %></small>
    </h3>
  </div>
</div>
<hr>

<h3>Answers</h3>
<% @answers.each do |answer| %>
  <div class="row">
    <div class="col-xs-2 answer-voting">
      <%= render 'layouts/formArrows', :object => [@question, answer] %>
    </div>
    <div class="col-xs-10">
      <pre>
        <%= answer.content %>
      </pre>
      By: <%= answer.user.username %>
      <i><%= answer.created_at.strftime("created on %m/%d/%Y at %I:%M%p") %></i>
      <strong>Current Votes: <%= answer.vote_count %></strong>
      <hr>
    </div>
  </div>
<% end %>

<hr>
<% if current_user %>
  <h3>
    <%= link_to "Add Answer", new_question_answer_path(@question) %>
  </h3>
<% else %>
 <p>
   <%= link_to 'Sign In', sign_in_path %> to Answer this Question
 </p>
<% end %>

app/views/users/index.html.erb
<h1>Welcome</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "layouts/errors", :object => @user %>

<%=form_for @user do |f| %>
  <%=f.label :username %>
  <%=f.text_field :username, :autofocus => 'autofocus' %>
  <%=f.label :email %>
  <%=f.text_field :email %>
  <%=f.label :password %>
  <%=f.password_field :password %>
  <%=f.label :password_confirmation %>
  <%=f.password_field :password_confirmation %>
  <%=f.submit "Sign Up" %>
<%end%>

app/views/users/show.html.erb
Hi, <%= @user.username %>!

<p>
  Here's your current info:

  Email: <%= @user.email %>
</p>

<% if @user.questions.any? %>
  <h3>Here are your Questions:</h3>
  <ul>
    <% @user.questions.each do |question| %>
      <li><%= link_to question.title, question_path(question) %></li>
    <% end %>
  </ul>
<% end %>

<% if @user.answers.any? %>
  <h3>Here are the Questions you've submitted answers for:</h3>
  <ul>
    <% @user.answers.each do |answer| %>
      <li><%= link_to answer.question.title, question_path(answer.question) %></li>
    <% end %>
  </ul>
<% end %>